In [3]:
import numpy as np

X=[]
Y=[]
for i in range(6):
    lst = list(range(i,i+4))
    X.append(list(map(lambda c: [c/10],lst)))
    Y.append((i+4)/10)

In [4]:
X=np.array(X)
Y=np.array(Y)
for i in range(len(X)):
    print((X[i],Y[i]))

(array([[0. ],
       [0.1],
       [0.2],
       [0.3]]), 0.4)
(array([[0.1],
       [0.2],
       [0.3],
       [0.4]]), 0.5)
(array([[0.2],
       [0.3],
       [0.4],
       [0.5]]), 0.6)
(array([[0.3],
       [0.4],
       [0.5],
       [0.6]]), 0.7)
(array([[0.4],
       [0.5],
       [0.6],
       [0.7]]), 0.8)
(array([[0.5],
       [0.6],
       [0.7],
       [0.8]]), 0.9)


In [10]:
import keras
from keras import layers
import tensorflow as tf

model = keras.models.Sequential([
    keras.layers.SimpleRNN(units=64,return_sequences=False,
                           input_shape=[4,1]),
    keras.layers.Dense(1)
])
model.compile(optimizer='adam',loss='mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 64)                4224      
                                                                 
 dense_1 (Dense)             (None, 1)                 65        
                                                                 
Total params: 4,289
Trainable params: 4,289
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(X,Y,epochs=300,verbose=0)


In [14]:
print(model.predict(X))

1/1 [==============================] - 0s 12ms/step
[[0.39489317]
 [0.50079715]
 [0.60415137]
 [0.70453113]
 [0.801377  ]
 [0.8940136 ]]
