In [2]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding,Conv1D,Dropout,MaxPooling1D,Activation
from keras.datasets import imdb
from keras.utils import pad_sequences
from keras.callbacks import EarlyStopping

import numpy as np
import matplotlib.pyplot as plt


In [3]:
#데이터를 불러와 학습셋,데이터셋으로 나눕니다.
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=5000)

In [5]:
#단어의 수를 맞추어 줍니다.
X_train = pad_sequences(X_train,maxlen=500)
X_test = pad_sequences(X_test,maxlen=500)
print(X_train)

[[   0    0    0 ...   19  178   32]
 [   0    0    0 ...   16  145   95]
 [   0    0    0 ...    7  129  113]
 ...
 [   0    0    0 ...    4 3586    2]
 [   0    0    0 ...   12    9   23]
 [   0    0    0 ...  204  131    9]]


In [6]:
#모델의 구조를 설정합니다.
model =Sequential()
model.add(Embedding(5000,100))
model.add(Dropout(0.5))
model.add(Conv1D(64,5,padding='valid',activation='relu',strides=1))
model.add(MaxPooling1D(pool_size=4))
model.add(LSTM(55))
model.add(Dense(1))
model.add(Activation('sigmoid'))

In [7]:
#모델의 실행 옵션을 정합니다.
model.compile(loss='categorical_crossentropy',optimizer='adam',
              metrics=['accuracy'])

In [8]:
#학습의 조기 중단을 설정
early_sttopping_callback = EarlyStopping(monitor='val_loss',patience=3)

In [1]:
#모델을 실행합니다.
history = model.fit(X_train,y_train,batch_size=40,epochs=100,validation_split=0.25,
                    callbacks=[early_sttopping_callback])

NameError: name 'model' is not defined

In [ ]:
#테스트 정확도를 출력합니다.
print('\n Test Accuracy:%.4f'%(model.evaluate(X_test,y_test)[1]))

In [ ]:
#점증셋과 학습셋의 오차를 저장합니다.
y_vloss =history.history['val_loss']

y_loss = history.history['loss']


In [ ]:
#그래프로 표현해 보겠습니다.
x_len = np.arange(len(y_loss))

plt.plot(x_len,y_vloss,marker='.',c='red',label='Testset_loss')
plt.plot(x_len,y_loss,marker='.',c='blue',label='Trainset_loss')
#그래프에 그리드를 주고 레이블을 표시
plt.legend(loc='upper right')
plt.grid()
plt.xlabel('epoch')
plt.ylabel('loss')
plt.show()