In [1]:
from keras.preprocessing.text import text_to_word_sequence


In [2]:
#전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'


In [4]:
#해당 텍스트를 토큰화합니다.
result =text_to_word_sequence(text)
print('\n원문 : \n',text)
print('\n토큰화: \n',result)


원문 : 
 해보지 않으면 해낼 수 없다

토큰화: 
 ['해보지', '않으면', '해낼', '수', '없다']


In [5]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',]

In [6]:
from keras.preprocessing.text import Tokenizer
token = Tokenizer()
token.fit_on_texts(docs)
print('\n단어 카운트\n',token.word_counts)


단어 카운트
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [7]:
print('\n문장 카운트 : ',token.document_count)


문장 카운트 :  3


In [8]:
print('\n 단어가 몇 개의 문장에 포함되어 있는가 : \n',token.word_docs)


 단어가 몇 개의 문장에 포함되어 있는가 : 
 defaultdict(<class 'int'>, {'단어를': 1, '각': 1, '토큰화합니다': 1, '나누어': 1, '먼저': 1, '텍스트의': 2, '토큰화해야': 1, '딥러닝에서': 2, '단어로': 1, '인식됩니다': 1, '있습니다': 1, '사용할': 1, '수': 1, '토큰화한': 1, '결과는': 1})


In [9]:
print('\n각 단어에 매겨진 인덱스 값:\n',token.word_index)


각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [14]:
#원핫 인코딩
text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'
token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [15]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [17]:
from keras.utils import to_categorical
#인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index)+1
x = to_categorical(x,num_classes=word_size)
print(x)

[[[[1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]]

  [[1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0.]
  

In [31]:
from keras.layers import Embedding
from keras.models import Sequential
from numpy import array
model = Sequential()
model.add(Embedding(16,4))

In [32]:
docs = ['너무 재밌네요','최고예요','참 잘 만든 영화에요','추천하고 싶은 영화입니다',
        '한번 더 보고싶네요','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요',
        '재미없어요']
#긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

In [33]:
#토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [34]:
x = token.texts_to_sequences(docs)
print('\n리뷰 테스트, 토큰화 결과 : \n',x)


리뷰 테스트, 토큰화 결과 : 
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [35]:
from keras.utils import pad_sequences
padded_x = pad_sequences(x,4)#서로의 다른길이의 데이터를 4로 맞추기
print('\n패딩 결과:\n',padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [36]:
word_size = len(token.word_index)+1

In [37]:
Embedding(word_size,8,input_length=4)

In [38]:
#단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력합니다.
from keras.layers import Dense,Flatten
model = Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 8)              168       
                                                                 
 flatten_1 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(padded_x,classes,epochs=20)
print('\n Accuracy : %.4f'%(model.evaluate(padded_x,classes)[1]))

Epoch 1/20
1/1 [==============================] - 0s 205ms/step - loss: 0.6498 - accuracy: 0.9000
Epoch 2/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6476 - accuracy: 0.9000
Epoch 3/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6455 - accuracy: 0.9000
Epoch 4/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6433 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 19ms/step - loss: 0.6411 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6390 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6368 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6345 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6323 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6301 - accuracy: 0.9000
Epoch 11/20
1/1 [============