In [15]:
import pandas as pd
data = pd.read_csv('../data/review_data.csv')

In [16]:
data.head()

score                      review  y
0      5            친절하시고 깔끔하고 좋았습니다  1
1      5                  조용하고 고기도 굿  1
2      4      갈비탕과 냉면, 육회비빔밥이 맛있습니다.  1
3      4  대체적으로 만족하나\n와인의 구성이 살짝 아쉬움  1
4      5       고기도 맛있고 서비스는 더 최고입니다~  1

In [17]:
data =data.drop(['score'],axis=True)

In [18]:
data.head()

review  y
0            친절하시고 깔끔하고 좋았습니다  1
1                  조용하고 고기도 굿  1
2      갈비탕과 냉면, 육회비빔밥이 맛있습니다.  1
3  대체적으로 만족하나\n와인의 구성이 살짝 아쉬움  1
4       고기도 맛있고 서비스는 더 최고입니다~  1

In [40]:
import re
data['review']=[re.sub('[^A-Za-z0-9가-힣]', ' ', s) for s in data['review']]
data['review']=data['review'].replace('  ','')

In [76]:
print(data)

                                                review  y
0                                     친절하시고 깔끔하고 좋았습니다  1
1                                           조용하고 고기도 굿  1
2                               갈비탕과 냉면  육회비빔밥이 맛있습니다   1
3                            대체적으로 만족하나 와인의 구성이 살짝 아쉬움  1
4                                고기도 맛있고 서비스는 더 최고입니다   1
..                                                 ... ..
540                                 추웟어요 고기 외에는 별로에요    0
541  고기질과 육전은 좋다 다만 한우손님 돼지고기 손님을 차별한다 돼지손님은 주차불가 네...  0
542          직접 구워주시고 진짜맛있음  반찬도 맛있음  직원분이 친절하게 잘해주시네요  1
543                           친절하게 서빙해주시고 음식도 챙겨주셨어요    1
544  강남역 점례네 방문 육회비빔밥은 맛있었당 뼈삼겹도 맛있었다  다만 부산본점이랑은 좀...  1

[545 rows x 2 columns]


In [42]:
from keras.preprocessing.text import text_to_word_sequence
from keras.preprocessing.text import Tokenizer

token = Tokenizer()
token.fit_on_texts(data['review'])

In [43]:
print(token.word_index)

{'너무': 1, '잘': 2, '정말': 3, '맛있어요': 4, '또': 5, '맛있게': 6, '맛있고': 7, '고기도': 8, '고기': 9, '다': 10, '좋았습니다': 11, '진짜': 12, '맛있었어요': 13, '서비스': 14, '친절하고': 15, '서비스도': 16, '좋고': 17, '친절하시고': 18, '맛있었습니다': 19, '좀': 20, '좋았어요': 21, '먹었습니다': 22, '역시': 23, '많이': 24, '맛도': 25, '좋아요': 26, '먹고': 27, '맛은': 28, '고기가': 29, '더': 30, '좋은': 31, '다만': 32, '직원분들도': 33, '갔는데': 34, '맛': 35, '맛이': 36, '다음에': 37, '조금': 38, '음식도': 39, '같아요': 40, '맛있습니다': 41, '아주': 42, '맛있는': 43, '고기는': 44, '수': 45, '분위기': 46, '구워주시고': 47, '매우': 48, '먹는': 49, '분위기도': 50, '예약하고': 51, '없이': 52, '최고': 53, '직접': 54, '완전': 55, '있는': 56, '늘': 57, '자주': 58, '넘': 59, '네이버': 60, '엄청': 61, '다른': 62, '구워주셔서': 63, '언제나': 64, '것': 65, '모두': 66, '고기를': 67, '맛있네요': 68, '다시': 69, '잘먹었습니다': 70, '같이': 71, '미리': 72, '꼭': 73, '감사합니다': 74, '깔끔하고': 75, '맛있어서': 76, '여기': 77, '먹었는데': 78, '많아서': 79, '처음': 80, '먹었어요': 81, '친절하게': 82, '비해': 83, '갈게요': 84, '직원분들이': 85, '좋았고': 86, '서비스는': 87, '너무너무': 88, '오랜만에': 89, '특히': 90, '바로': 91, '굉장히': 92, '만족합니다': 93

In [44]:
x = token.texts_to_sequences(data['review'])
print(x)
a=0
for index in x:
    if a<len(index):
        a=len(index)
print(a)


[[18, 75, 11], [395, 8, 396], [746, 397, 747, 41], [748, 749, 750, 177, 250, 751], [8, 7, 87, 30, 178], [29, 398, 752, 16, 179], [398, 753, 754, 755], [8, 756, 136, 137], [399, 757, 758, 400, 401, 31, 759, 760, 761, 42, 762, 251, 9, 402, 252, 763, 32, 138, 764, 765, 766, 767, 58, 180, 403, 97, 768], [769, 36, 42, 11, 253, 770, 771, 9, 181, 772, 773, 182, 774, 775, 776, 404, 23, 777, 778, 779, 780, 781, 139, 140, 254, 782, 783, 784, 785, 786, 787, 788, 789], [4, 98, 790, 791, 792, 19], [50, 255, 9, 793, 17, 141, 405, 794, 183, 795, 796], [29, 88, 19, 797, 798, 799, 184, 800, 3, 178, 58, 801], [67, 256, 802, 803, 804, 805, 406, 806, 257, 807, 16, 808, 809, 16, 258, 185, 407, 259, 810, 142, 99, 811, 812, 260, 813], [89, 814, 815, 816, 408, 186, 817, 818, 819, 14, 820, 261, 821, 822, 409, 823, 23, 262, 23, 261, 263, 824, 825], [43, 410, 411, 826, 11, 827, 828, 264], [829], [265, 187, 188, 830, 831, 412, 413, 48, 832, 833, 834, 835, 836, 48, 837, 28, 838, 839, 414, 24, 840, 841, 842, 415], 

In [48]:
from keras.utils import pad_sequences
classes = data['y'].to_numpy()


In [55]:
#패딩
from keras.utils import pad_sequences
padded_x = pad_sequences(x)#서로의 다른길이의 데이터를 4로 맞추기
print('\n패딩 결과:\n',padded_x)
padded_x.shape


패딩 결과:
 [[   0    0    0 ...   18   75   11]
 [   0    0    0 ...  395    8  396]
 [   0    0    0 ...  397  747   41]
 ...
 [   0    0    0 ...  164   82 3720]
 [   0    0    0 ... 3721   39 3722]
 [   0    0    0 ... 3727   20 3728]]


(545, 84)

In [50]:
word_size = len(token.word_index)+1

In [51]:
from keras.layers import Dense,Flatten
from keras.layers import Embedding
from keras.models import Sequential
model = Sequential()
model.add(Embedding(word_size,8,input_length=84))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 84, 8)             29832     
                                                                 
 flatten_1 (Flatten)         (None, 672)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 673       
                                                                 
Total params: 30,505
Trainable params: 30,505
Non-trainable params: 0
_________________________________________________________________


In [52]:
model.compile(optimizer='adam',loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(padded_x,classes,epochs=100)
print('\n Accuracy : %.4f'%(model.evaluate(padded_x,classes)[1]))

Epoch 1/100
18/18 [==============================] - 0s 8ms/step - loss: 0.6191 - accuracy: 0.9046
Epoch 2/100
18/18 [==============================] - 0s 7ms/step - loss: 0.4457 - accuracy: 0.9064
Epoch 3/100
18/18 [==============================] - 0s 6ms/step - loss: 0.3105 - accuracy: 0.9064
Epoch 4/100
18/18 [==============================] - 0s 5ms/step - loss: 0.2720 - accuracy: 0.9064
Epoch 5/100
18/18 [==============================] - 0s 5ms/step - loss: 0.2662 - accuracy: 0.9064
Epoch 6/100
18/18 [==============================] - 0s 4ms/step - loss: 0.2590 - accuracy: 0.9083
Epoch 7/100
18/18 [==============================] - 0s 4ms/step - loss: 0.2512 - accuracy: 0.9119
Epoch 8/100
18/18 [==============================] - 0s 4ms/step - loss: 0.2418 - accuracy: 0.9156
Epoch 9/100
18/18 [==============================] - 0s 4ms/step - loss: 0.2325 - accuracy: 0.9156
Epoch 10/100
18/18 [==============================] - 0s 4ms/step - loss: 0.2210 - accuracy: 0.9211
Epoch 11/

In [82]:
text = '추웟어요 고기 외에는 별로에요'
token = Tokenizer()
token.fit_on_texts([text])
y = token.texts_to_sequences([text])
print(y)

[[1, 2, 3, 4]]


In [83]:
padded_y = pad_sequences(y,84)
y_predict = model.predict(padded_y)
print(y_predict)


1/1 [==============================] - 0s 10ms/step
[[0.9996983]]
